# Generated by Django 3.1.7 on 2023-05-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_tareamayo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tareamayo',
            new_name='Tarea_mayo',
        ),
    ]
