from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('editar_tarea/<str:pk>', views.editar_tarea, name="editar_tarea"),
    path('eliminar_tarea/<str:pk>', views.eliminar_tarea, name="eliminar_tarea"),
    path('enero/', views.enero, name="enero"),
    path('febrero/', views.febrero, name="febrero"),
    path('editar_tarea1/<str:pk>', views.editar_tarea1, name="editar_tarea1"),
    path('eliminar_tarea1/<str:pk>', views.eliminar_tarea1, name="eliminar_tarea1"),
    path('mayo/', views.mayo, name="mayo"),
    path('editar_tarea_mayo/<str:pk>', views.editar_tarea_mayo, name="editar_tarea_mayo"),
    path('eliminar_tarea_mayo/<str:pk>', views.eliminar_tarea_mayo, name="eliminar_tarea_mayo"),
    path('marzo/', views.marzo, name="marzo"),
    path('editar_tarea_marzo/<str:pk>', views.editar_tarea_marzo, name="editar_tarea_marzo"),
    path('eliminar_tarea_marzo/<str:pk>', views.eliminar_tarea_marzo, name="eliminar_tarea_marzo"),
    path('abril/', views.abril, name="abril"),
    path('editar_tarea_abril/<str:pk>', views.editar_tarea_abril, name="editar_tarea_abril"),
    path('eliminar_tarea_abril/<str:pk>', views.eliminar_tarea_abril, name="eliminar_tarea_abril"),
    path('junio/', views.junio, name="junio"),
    path('editar_tarea_junio/<str:pk>', views.editar_tarea_junio, name="editar_tarea_junio"),
    path('eliminar_tarea_junio/<str:pk>', views.eliminar_tarea_junio, name="eliminar_tarea_junio"),
    path('julio/', views.julio, name="julio"),
    path('editar_tarea_julio/<str:pk>', views.editar_tarea_julio, name="editar_tarea_julio"),
    path('eliminar_tarea_julio/<str:pk>', views.eliminar_tarea_julio, name="eliminar_tarea_julio"),
    path('agosto/', views.agosto, name="agosto"),
    path('editar_tarea_agosto/<str:pk>', views.editar_tarea_agosto, name="editar_tarea_agosto"),
    path('eliminar_tarea_agosto/<str:pk>', views.eliminar_tarea_agosto, name="eliminar_tarea_agosto"),
    path('septiembre/', views.septiembre, name="septiembre"),
    path('editar_tarea_septiembre/<str:pk>', views.editar_tarea_septiembre, name="editar_tarea_septiembre"),
    path('eliminar_tarea_septiembre/<str:pk>', views.eliminar_tarea_septiembre, name="eliminar_tarea_septiembre"),
    path('octubre/', views.octubre, name="octubre"),
    path('editar_tarea_octubre/<str:pk>', views.editar_tarea_octubre, name="editar_tarea_octubre"),
    path('eliminar_tarea_octubre/<str:pk>', views.eliminar_tarea_octubre, name="eliminar_tarea_octubre"),
    path('noviembre/', views.noviembre, name="noviembre"),
    path('editar_tarea_noviembre/<str:pk>', views.editar_tarea_noviembre, name="editar_tarea_noviembre"),
    path('eliminar_tarea_noviembre/<str:pk>', views.eliminar_tarea_noviembre, name="eliminar_tarea_noviembre"),
    path('diciembre/', views.diciembre, name="diciembre"),
    path('editar_tarea_diciembre/<str:pk>', views.editar_tarea_diciembre, name="editar_tarea_diciembre"),
    path('eliminar_tarea_diciembre/<str:pk>', views.eliminar_tarea_diciembre, name="eliminar_tarea_diciembre")
]